export const lightTheme = {
  white: '#ffffff',
  background: '#ffffff',
  text: '$dark500',
  textWeak: '$gray900',

  // Naming of the colors below has been influenced by NextUI:
  // secondaryLight: '$purple200',
  // secondaryLightHover: '$purple300',
  // secondaryLightActive: '$purple400',
  // secondaryLightContrast: '$purple600',
  // secondary: '$purple600',
  // secondaryBorder: '$purple500',
  // secondaryBorderHover: '$purple600',
  // secondarySolidHover: '$purple700',
  // secondarySolidContrast: '$white',

  primary: '$blue500',
  primaryContrast: '$white',
  primarySolid: '$blue600',
  primaryBorder: '$blue500',
  primaryLight: '$blue200',
  primaryLightHover: '$blue300',
  primaryBackground: '$blue100',
  primaryText: '$blue900',

  secondary: '$dark500',
  secondaryContrast: '$white',
  secondarySolid: '$dark600',
  secondaryBorder: '$dark500',
  secondaryLight: '$dark200',
  secondaryLightHover: '$dark300',
  secondaryBackground: '$dark100',
  secondaryText: '$dark900',

  neutral: '$gray700',
  neutralContrast: '$white',
  neutralSolid: '$dark600',
  neutralBorder: '$gray500',
  neutralBorderHover: '$gray600',
  neutralLight: '$gray300',
  neutralLightHover: '$gray400',
  neutralBackground: '$gray200',
  neutralText: '$gray900',

  success: '$green600',
  successContrast: '$white',
  successSolid: '$green700',
  successBorder: '$green500',
  successLight: '$green200',
  successLightHover: '$green300',
  successBackground: '$green100',
  successText: '$green900',

  warning: '$yellow600',
  warningContrast: '$white',
  warningSolid: '$yellow700',
  warningBorder: '$yellow500',
  warningLight: '$yellow200',
  warningLightHover: '$yellow300',
  warningBackground: '$yellow100',
  warningText: '$yellow900',

  error: '$red600',
  errorContrast: '$white',
  errorSolid: '$red700',
  errorBorder: '$red500',
  errorLight: '$red200',
  errorLightHover: '$red300',
  errorBackground: '$red100',
  errorText: '$red700',

  negative: '$white',
  negativeContrast: '$blue500',
  negativeSolid: '$white',
  negativeBorder: '$white',
  negativeLight: '$white',
  negativeLightHover: '$white',
  negativeBackground: '$white',
  negativeText: '$white',
};
