import { palette } from "./palette";

const { blue, green, yellow, red, darkblue, gray, sequential } = palette;

export const lightTheme = {
  white: "#ffffff",
  background: "#ffffff",
  text: "$dark500",
  textWeak: "$gray900",

  // Naming of the colors below has been influenced by NextUI:
  // secondaryLight: '$purple200',
  // secondaryLightHover: '$purple300',
  // secondaryLightActive: '$purple400',
  // secondaryLightContrast: '$purple600',
  // secondary: '$purple600',
  // secondaryBorder: '$purple500',
  // secondaryBorderHover: '$purple600',
  // secondarySolidHover: '$purple700',
  // secondarySolidContrast: '$white',

  primary: "$blue500",
  primaryContrast: "$white",
  primarySolid: "$blue600",
  primaryBorder: "$blue500",
  primaryLight: "$blue200",
  primaryLightHover: "$blue300",
  primaryBackground: "$blue100",
  primaryText: "$blue900",

  secondary: "$dark500",
  secondaryContrast: "$white",
  secondarySolid: "$dark600",
  secondaryBorder: "$dark500",
  secondaryLight: "$dark200",
  secondaryLightHover: "$dark300",
  secondaryBackground: "$dark100",
  secondaryText: "$dark900",

  neutral: "$gray700",
  neutralContrast: "$white",
  neutralSolid: "$dark600",
  neutralBorder: "$gray500",
  neutralBorderHover: "$gray600",
  neutralLight: "$gray300",
  neutralLightHover: "$gray400",
  neutralBackground: "$gray200",
  neutralText: "$gray900",

  success: "$green600",
  successContrast: "$white",
  successSolid: "$green700",
  successBorder: "$green500",
  successLight: "$green200",
  successLightHover: "$green300",
  successBackground: "$green100",
  successText: "$green900",

  warning: "$yellow600",
  warningContrast: "$white",
  warningSolid: "$yellow700",
  warningBorder: "$yellow500",
  warningLight: "$yellow200",
  warningLightHover: "$yellow300",
  warningBackground: "$yellow100",
  warningText: "$yellow900",

  error: "$red600",
  errorContrast: "$white",
  errorSolid: "$red700",
  errorBorder: "$red500",
  errorLight: "$red200",
  errorLightHover: "$red300",
  errorBackground: "$red100",
  errorText: "$red700",

  negative: "$white",
  negativeContrast: "$blue500",
  negativeSolid: "$white",
  negativeBorder: "$white",
  negativeLight: "$white",
  negativeLightHover: "$white",
  negativeBackground: "$white",
  negativeText: "$white",
};

export const theme = {
  colors: {
    ...blue,
    ...green,
    ...yellow,
    ...red,
    ...darkblue,
    ...gray,
    ...sequential,
    ...lightTheme,
  },
  space: {
    0: "4px",
    1: "6px",
    2: "8px",
    3: "12px",
    4: "16px",
    5: "20px",
    6: "24px",
    7: "32px",
    // 36px is used too for large inputs and buttons
    8: "40px",
  },
  fontSizes: {
    base: "16px",
    lead: "18px",
    xs: "10px",
    s: "12px",
    m: "16px",
    l: "20px",
    xl: "24px",
    xxl: "32px",
    xxxl: "40px",
    appname: "21px", // weird...
  },
  fonts: {
    primary: "Inter, Avenir, Helvetica, Arial, sans-serif",
    secondary: "Lato, sans-serif",
  },
  fontWeights: {
    bolder: 700,
    bold: 600,
    medium: 500,
    regular: 400,
    light: 300,
    lighter: 200,
  },
  lineHeights: {
    xs: "12px",
    s: "15px",
    m: "18px",
    l: "22px",
    btn: "24px",
    xl: "30px",
    xxl: "40px",
    appname: "21px", // weird...
  },
  letterSpacings: {
    base: "0.5px",
  },
  sizes: {
    4: "4px",
    16: "16px",
    24: "24px",
  },
  borderWidths: {
    1: "1px",
    2: "2px",
  },
  borderStyles: {},
  radii: {
    1: "4px",
    2: "6px",
    3: "8px",
    8: "8px",
    12: "12px",
    16: "16px",
    24: "24px",
    32: "32px",
  },
  shadows: {
    btn: "0px 0px 4px rgba(50, 66, 82, 0.4)",
    md: "0px 0px 8px rgba(50, 66, 82, 0.4)", // dark600 @ 40%
    lt: "2px 2px 4px rgba(153, 153, 153, 0.4)",
    vlt: "2px 2px 4px 0px rgba(153, 153, 153, 0.161)",
  },
  zIndices: {
    1: "100",
    2: "200",
    3: "300",
    4: "400",
    5: "500",
    drawer: "200",
    appbar: "300",
    modal: "500",
    toast: "600",
  },
  transitions: {},
  tiles: {
    padding: 16,
    headerHeight: 40,
    border: 1,
  },
  charts: {
    backgroundColor: "#fff",
    axisColor: gray.gray400,
    gridColor: gray.gray400,
    gridStrokeDashArray: "10, 5",
    brushColor: blue.blue400,
    crosshairColor: blue.blue400,
  },
};
